url: https://jeffgorrell.github.io
baseurl: /testing1/

# Site settings
title: IT Ninja
email: buzz@itninja.pro
description: "itninja.pro automates technology to keep things simple."


# Team names, titles and social links
people:
- name: Jeff
  pic: 1
  position: Master Ninja
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/itninjapro
  - title: facebook
    url: http://facebook.com/itninjapro
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/itninjapro
  - title: bitbucket 
    url: http://bitbucket.org/itninjapro
  - title: github
    url: http://github.com/itninjapro

# Postal address (add as many lines as necessary)
address:
  - line: Brisbane
  - line: Queensland, Australia

# Build settings
markdown: kramdown
permalink: pretty
